
window.customElements.define("talentics-icons-computer-edit", require('./icons/ComputerEdit').default)
window.customElements.define("talentics-icons-copy", require('./icons/Copy').default)
window.customElements.define("talentics-icons-detail", require('./icons/Detail').default)
window.customElements.define("talentics-icons-github", require('./icons/Github').default)
window.customElements.define("talentics-icons-not-verified", require('./icons/NotVerified').default)
window.customElements.define("talentics-icons-npm", require('./icons/Npm').default)
window.customElements.define("talentics-icons-verified", require('./icons/Verified').default)
window.customElements.define("talentics-icons-whatsapp", require('./icons/Whatsapp').default)
window.customElements.define("talentics-illustrations-confirmation", require('./illustrations/Confirmation').default)
window.customElements.define("talentics-illustrations-duplicate-item", require('./illustrations/DuplicateItem').default)